owner: icroptec
repo: uptime-monitor

sites:
  - name: Vision
    url: http://vision.icrop.online
  - name: Power
    url: https://icroppower.icrop.com.br
  - name: Icrop Website
    url: https://icrop.com.br
  - name: IOT
    url: https://iot.icrop.com.br
  - name: Feedz
    url: https://app.feedz.com.br

status-website:
  baseUrl: /uptime-monitor
  logoUrl: https://icrop.com.br/franquias/2/30340/editor-html/8940638.png
  name: Uptime Monitor
  theme: night
  navbar:
    - title: IARA
      href: https://wa.me/553432100520

robotsText: "User-agent: *"
