owner: icroptec
repo: uptime-monitor

sites:
  - name: Icrop Website
    url: https://icrop.com.br
  - name: Vision
    url: https://vision.icrop.online
  - name: Power
    url: https://icroppower.icrop.com.br

status-website:  
  baseUrl: /uptime-monitor
  logoUrl: https://icrop.com.br/franquias/2/30340/editor-html/8940638.png
  name: Uptime Monitor  
  theme: night
  navbar:
    - title: Status
      href: https://icrop.com.br    

robotsText: "User-agent: *"
