owner: icroptec
repo: uptime-monitor

sites:
  - name: Vision (vision.icrop.online)
    check: "tcp-ping"
    url: 34.49.19.147
    port: 80
  - name: Power
    url: https://icroppower.icrop.com.br
  - name: Power Backend
    url: https://icroppower.icrop.com.br/api/v1
  - name: API Python Power
    url: https://icroppower.icrop.com.br/py/api/v1/health
  - name: Icrop Website (icrop.com.br)
    url: https://icrop.com.br
  - name: Automation.icrop.ai
    check: "tcp-ping"
    url: 3.82.141.244
    port: 80
  - name: iCrop AgroBI
    url: https://icrop.agrobi.net/
  - name: Mural iCrop
    url: https://mural.icrop.com.br
  - name: Feedz
    url: https://app.feedz.com.br

status-website:
  baseUrl: /uptime-monitor
  logoUrl: https://icrop.com.br/wp-content/uploads/2023/05/logo-icrop.png
  name: iCrop Uptime Monitor
  theme: night
  navbar:
    - title: IARA
      href: https://wa.me/5508003210520

robotsText: "User-agent: *"
