owner: icroptec
repo: uptime-monitor

sites:
  - name: Vision (vision.icrop.online)
    check: "tcp-ping"
    url: 34.49.19.147
    port: 80
  - name: Kill
    url: https://kill.icrop.ai
  - name: Vision app
    url: https://app23.icrop.online/home
  - name: Power
    url: https://icroppower.icrop.com.br
  - name: Icrop Website (icrop.com.br)
    url: https://icrop.com.br
  - name: Pivot Design
    url: https://pivotdesign.icrop.online
  - name: Mural iCrop
    url: https://mural.icrop.com.br
  - name: Aplicativo Vision
    url: https://app23.icrop.online

status-website:
  baseUrl: /
  logoUrl: https://icrop.com.br/wp-content/uploads/2023/05/logo-icrop.png
  name: iCrop Uptime Monitor
  theme: night
  navbar:
    - title: IARA
      href: https://wa.me/5508003210520

robotsText: "User-agent: *"
